import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Card from '../components/Card';
import { CardType } from '../Types/CardType';
import { GetStaticProps } from 'next';
export const getStaticProps:GetStaticProps = async () => {
    const sportArticles = await fetch('https://anderspink.com/code-test/data/sports.json?errors=0').then(res => {
        if(res.ok) return res.json();
        return [];
    });
    const marketingArticles = await fetch('https://anderspink.com/code-test/data/marketing.json?errors=0').then(res => {
        if (res.ok) return res.json();
        return [];
    });
    const environmentArticles = await fetch('https://anderspink.com/code-test/data/marketing.json?errors=0').then(res => {
        if (res.ok) return res.json();
        return [];
    });
    const articles = [...sportArticles, ...marketingArticles, ...environmentArticles];
    return {
        props: {
            articles: articles
        }
    }
}
export default function Home({ articles }:any) {
  return (
    <>
      <Head>
        <title>Article Feed app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id={styles.container}>
        <h1 id={styles.title}>Articles Archive</h1>
        { articles.map((article:CardType, index:number) => (
            <Card
                key={index}
                image={article.image}
                title={article.title}
                domain={article.domain}
                date={article.date}
                content={article.content}
                tag="Sports"
            />
        ))}
      </main>
    </>
  )
}
